### ISSUE TITLE
Ownership reset for entire server

### ISSUE THREAD

**Issue by alaw005** [joeybaker/docker-syncthing#1]
Just a warning. The following lines in start.sh reset ownership of all files on my server. 
# set permissions so that we have access to volumes

chown -R syncthing:users /srv/config /srv/data 
chmod -R 770 /srv/config /srv/data

**Comment by joeybaker** [comment]
Hmmm… what's the issue here? The files need to be owned and accessible to syncthing. Otherwise, nothing works :)

**Comment by alaw005** [comment]
I understand. The issue is that if you set the data volume /srv/data to say mnt/data on the host this will change the owner of ALL files on host to "22000:user". This may be desirable for some but in my case has lead to a large task of changing ownership back - it was my fault as should have selected a much smaller folder to start with but a warning on the readme page might help others might. I wonder if an alternative approach might be to add the new syncthing user into an existing group on the host - and whether this can be passed in as an environment variable? I'm no expert though.

**Comment by joeybaker** [comment]
Gotcha. That's fair. 

A warning in the readme is a good idea. If you have the time for a PR on a smarter way to set ownership, I'd happily take it!

**Comment by castorinop** [comment]
can be optional ? 
in my case a lagre number of files and dirs are syncing and every start the container takes hours on change permissions.

**Comment by joeybaker** [comment]
@castorinop All the files need to be owned by the `synching:users` and the permissions need to be `770` or synching won't have access to them. I supposed you could add in a bit of code that checks for the permissions of the top level directory, and if they're correct assume that the permissions of everything lower down is correct too, but that seems error-prone. 

I'm open to suggestions though!
