### ISSUE TITLE
What is suppose to happen on the 2nd, 3td, N machines

### ISSUE THREAD

**Issue by pascalandy** [joeybaker/docker-syncthing#13]
**Question** - What is suppose to happen on the 2nd, 3td, N machines? 

Here is what I did so far but I'm stocked. 

#### On ubuntu server #1

```
DIR_TO_SYNC="/mnt/syncdata/pics"
CFG_TO_SYNC="/mnt/syncdata/config"

mkdir -p $DIR_TO_SYNC
mkdir -p $CFG_TO_SYNC

ENV_PORT_ACTION=8080
sudo ufw allow $ENV_PORT_ACTION/tcp
ENV_PORT_ACTION=22000
sudo ufw allow $ENV_PORT_ACTION/tcp
ENV_PORT_ACTION=21025
sudo ufw allow $ENV_PORT_ACTION/udp
sudo ufw reload

docker run -d \
--name syncthing \
--restart=always \
-v $DIR_TO_SYNC:/srv/data \
-v $CFG_TO_SYNC:/srv/config \
-p 22000:22000  -p 21025:21025/udp -p 8080:8080 \
joeybaker/syncthing

```

Put a file to sync

```
root@N12-AMS1:/mnt/syncdata/pics# touch testn12.txt
root@N12-AMS1:/mnt/syncdata/pics# ls -la
total 12
drwxrwx--- 3 1027 users 4096 Dec 27 23:47 .
drwxr-xr-x 4 root root  4096 Dec 27 23:40 ..
-rw-r--r-- 1 root root     0 Dec 27 23:46 testn12.txt
```

Cool. Let's sync with the second machine.

#### On ubuntu server #2

```
DIR_TO_SYNC="/mnt/syncdata/pics"
CFG_TO_SYNC="/mnt/syncdata/config"

mkdir -p $DIR_TO_SYNC
mkdir -p $CFG_TO_SYNC

ENV_PORT_ACTION=8080
sudo ufw allow $ENV_PORT_ACTION/tcp
ENV_PORT_ACTION=22000
sudo ufw allow $ENV_PORT_ACTION/tcp
ENV_PORT_ACTION=21025
sudo ufw allow $ENV_PORT_ACTION/udp
sudo ufw reload

docker run -d \
...
?
?
?
?
```

Thank you!
twitter.com/_pascalandy

**Comment by pascalandy** [comment]
OK, I see we need to configure syncthing via the GUI https://docs.syncthing.net/intro/getting-started.html#configuring

I guess no there no way to only use Docker at this point right? You may close if it's the case.

Cheers!

**Comment by joeybaker** [comment]
You could setup the configure file you pass to docker to connect your two machines for you, but it would be hard to do that correctly without going through the GUI.

**Comment by pascalandy** [comment]
Got it. Thank you! Now that I understand syncthing better it make sense.

Cheers!
