### ISSUE TITLE
Following updates

### ISSUE THREAD

**Issue by pascalandy** [joeybaker/docker-syncthing#14]
Hi, 

I tried to [build](https://github.com/joeybaker/docker-syncthing/blob/master/Dockerfile#L5) this project using the latest version (0.14.17 at the moment) but the build failed.

Would it be possible to only update those to [values](https://github.com/joeybaker/docker-syncthing/blob/master/Dockerfile#L5) and build ?

```
- ENV SYNCTHING_VERSION
- ENV GOSU_VERSION
```

Cheers!

**Comment by joeybaker** [comment]
Try just updating the syncthing version. `gosu` is a little finicky.

**Comment by pascalandy** [comment]
This is what I did. 
I didn't update Gosu version.

**Comment by joeybaker** [comment]
@pascalandy hmmm… I'm not sure what this issue is. Docker hub just built v0.14.18 w/o a problem: https://hub.docker.com/r/joeybaker/syncthing/builds/bcahphsyqwqc9jmrwflqpve/

**Comment by pascalandy** [comment]
Thanks for letting me know. Will retry today.

**Comment by pascalandy** [comment]
All working good at this point! Takes for caring :)

**Comment by joeybaker** [comment]
Great!
