### ISSUE TITLE
Backslash paths in start.sh

### ISSUE THREAD

**Issue by eriklindqvist** [joeybaker/docker-syncthing#3]
The first sed command in start.sh to replace the path in config.xml from /root/Sync to/srv/data/default doesn't work because the path names need to be backslashed. Because of this, the second sed command is never executed, so nothing gets replaced.

``` bash
$ sed -e "s/id=\"default\" path=\"/root\/Sync\"/id=\"default\" path=\"/srv/data/default\"/" -i /srv/config/config.xml
sed: -e expression #1, char 36: unknown option to `s'
```

Change it like this to make it work

``` bash
sed -e "s/id=\"default\" path=\"\/root\/Sync\"/id=\"default\" path=\"\/srv\/data\/default\"/" -i /srv/config/config.xml
```

**Comment by joeybaker** [comment]
Thanks @eriklindqvist!
